name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:          # Allows manual trigger from the Actions tab
  push:
    branches:
      - main                  # Also runs when you push to main

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Generate the snake animation
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: fransanityvillareal   # your GitHub username
          outputs: dist/snake.svg

      # 3️⃣ Push the generated snake.svg to the "output" branch
      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output                   # branch where snake.svg will be stored
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
